export const SYSTEM_SCHEMA = [
    `CREATE TABLE IF NOT EXISTS config (chave TEXT PRIMARY KEY, valor TEXT);`,
    `CREATE TABLE IF NOT EXISTS app_settings (
        id INTEGER PRIMARY KEY CHECK (id = 1), 
        updated_at TEXT,
        primary_color TEXT DEFAULT '#059669',
        theme_mode TEXT DEFAULT 'system',
        fazenda_nome TEXT,
        fazenda_produtor TEXT,
        fazenda_documento TEXT,
        fazenda_telefone TEXT,
        fazenda_email TEXT,
        fazenda_logo TEXT,
        fin_moeda TEXT DEFAULT 'R$',
        fin_mes_fiscal INTEGER DEFAULT 1,
        fin_calc_margem INTEGER DEFAULT 0,
        fin_vinc_custo INTEGER DEFAULT 0,
        fin_meta_lucro REAL,
        clima_api_key TEXT,
        clima_cidade TEXT,
        clima_gps INTEGER DEFAULT 1,
        clima_ativo INTEGER DEFAULT 1,
        rel_incluir_logo INTEGER DEFAULT 1,
        rel_modelo TEXT DEFAULT 'resumido',
        img_qualidade REAL DEFAULT 0.8,
        img_limite INTEGER DEFAULT 3,
        fazenda_area REAL,
        fazenda_safra TEXT,
        unidade_padrao TEXT DEFAULT "KG",
        rel_graficos INTEGER DEFAULT 1,
        rel_auto_pdf INTEGER DEFAULT 0,
        rel_rodape TEXT
    );`,
    `CREATE TABLE IF NOT EXISTS v2_sync_queue (
        id TEXT PRIMARY KEY,
        table_name TEXT,
        operation TEXT,
        record_id TEXT,
        payload TEXT,
        status TEXT DEFAULT 'pending',
        retry_count INTEGER DEFAULT 0,
        created_at TEXT DEFAULT (datetime('now'))
    );`,
    `CREATE TABLE IF NOT EXISTS v2_sync_logs (
        id TEXT PRIMARY KEY,
        operation TEXT,
        table_name TEXT,
        status TEXT,
        message TEXT,
        created_at TEXT DEFAULT (datetime('now'))
    );`,
    `CREATE TABLE IF NOT EXISTS base_conhecimento_pro (
        uuid TEXT PRIMARY KEY, 
        tipo TEXT NOT NULL, 
        cultura_id TEXT, 
        titulo TEXT NOT NULL, 
        descricao TEXT, 
        sintomas TEXT, 
        causas TEXT, 
        controle TEXT, 
        fonte TEXT, 
        nivel_confianca TEXT, 
        ativo INTEGER DEFAULT 1, 
        last_updated TEXT NOT NULL, 
        sync_status INTEGER DEFAULT 0
    );`,
    `CREATE TABLE IF NOT EXISTS v2_error_logs (
        id TEXT PRIMARY KEY,
        tela TEXT,
        funcao TEXT,
        erro TEXT,
        stack TEXT,
        severity TEXT DEFAULT 'ERROR',
        created_at TEXT DEFAULT (datetime('now'))
    );`
];
