
-- Tabela de Usuários (Sincronizado via UUID, mas login local depende de senha hash)
CREATE TABLE IF NOT EXISTS usuarios (
    id bigint generated by default as identity primary key,
    usuario text unique not null,
    senha text not null, -- Hash Bcrypt
    nivel text default 'USUARIO',
    email text,
    nome_completo text,
    telefone text,
    endereco text,
    last_updated text
    -- sync_status não necessario na nuvem
);

-- Tabela de Colheitas (Consolidado)
CREATE TABLE IF NOT EXISTS colheitas (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    cultura text not null,
    produto text not null,
    quantidade numeric not null,
    congelado numeric default 0,
    data text not null, -- ISO String YYYY-MM-DD
    observacao text,
    last_updated text not null
);

-- Tabela de Vendas
CREATE TABLE IF NOT EXISTS vendas (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    cliente text not null,
    produto text not null,
    quantidade numeric not null,
    valor numeric not null,
    data text not null,
    observacao text,
    status text default 'ATIVA',
    last_updated text not null
);

-- Tabela de Compras
CREATE TABLE IF NOT EXISTS compras (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    item text not null,
    quantidade numeric not null,
    valor numeric not null,
    cultura text,
    data text not null,
    observacao text,
    unidade text,
    last_updated text not null
);

-- Tabela de Plantio
CREATE TABLE IF NOT EXISTS plantio (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    cultura text not null,
    quantidade_pes int not null,
    tipo_plantio text,
    data text not null,
    observacao text,
    last_updated text not null
);

-- Tabela de Custos (Serviços)
CREATE TABLE IF NOT EXISTS custos (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    produto text not null,
    tipo text,
    quantidade numeric not null,
    valor_total numeric not null,
    data text not null,
    observacao text,
    last_updated text not null
);

-- Tabela de Descarte
CREATE TABLE IF NOT EXISTS descarte (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    produto text not null,
    quantidade_kg numeric not null,
    motivo text,
    data text not null,
    last_updated text not null
);

-- Tabela de Cadastro (Insumos, Produtos, Serviços Base)
CREATE TABLE IF NOT EXISTS cadastro (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    nome text not null,
    unidade text,
    tipo text,
    estocavel int default 1,
    vendavel int default 1,
    observacao text,
    last_updated text not null
);

-- Tabela de Clientes
CREATE TABLE IF NOT EXISTS clientes (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    nome text not null,
    telefone text,
    endereco text,
    cpf_cnpj text,
    observacao text,
    last_updated text not null
);

-- Tabela de Culturas (Áreas)
CREATE TABLE IF NOT EXISTS culturas (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    nome text not null,
    observacao text,
    last_updated text not null
);

-- Tabela de Máquinas
CREATE TABLE IF NOT EXISTS maquinas (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    nome text not null,
    tipo text not null,
    placa text,
    horimetro_atual numeric default 0,
    intervalo_revisao numeric default 10000,
    status text default 'OK',
    last_updated text not null
);

-- Tabela de Manutenção de Frota
CREATE TABLE IF NOT EXISTS manutencao_frota (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    maquina_uuid text not null, -- FK Logica
    data text not null,
    descricao text not null,
    valor numeric not null,
    last_updated text not null
);

-- Permissões para que o Anon Key funcione
-- (Garante que o App consiga ler e escrever em todas as tabelas)
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;

-- Migração de compatibilidade com AgroGB Mobile 7.x / Desktop Sync
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS uuid uuid UNIQUE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS avatar text;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS avatar_url text;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS provider text DEFAULT 'local';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;

ALTER TABLE colheitas ADD COLUMN IF NOT EXISTS congelado numeric DEFAULT 0;
ALTER TABLE colheitas ADD COLUMN IF NOT EXISTS anexo text;
ALTER TABLE colheitas ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;

ALTER TABLE vendas ADD COLUMN IF NOT EXISTS anexo text;
ALTER TABLE vendas ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;

ALTER TABLE compras ADD COLUMN IF NOT EXISTS fornecedor_uuid text;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS detalhes text;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS anexo text;
ALTER TABLE compras ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;

ALTER TABLE plantio ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;

ALTER TABLE custos ADD COLUMN IF NOT EXISTS anexo text;
ALTER TABLE custos ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;

ALTER TABLE descarte ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;

ALTER TABLE cadastro ADD COLUMN IF NOT EXISTS fator_conversao numeric DEFAULT 1;
ALTER TABLE cadastro ADD COLUMN IF NOT EXISTS principio_ativo text;
ALTER TABLE cadastro ADD COLUMN IF NOT EXISTS composicao text;
ALTER TABLE cadastro ADD COLUMN IF NOT EXISTS classe_toxicologica text;
ALTER TABLE cadastro ADD COLUMN IF NOT EXISTS preco_venda numeric DEFAULT 0;
ALTER TABLE cadastro ADD COLUMN IF NOT EXISTS descricao_ia text;
ALTER TABLE cadastro ADD COLUMN IF NOT EXISTS validado_por text;
ALTER TABLE cadastro ADD COLUMN IF NOT EXISTS data_validacao text;
ALTER TABLE cadastro ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;

ALTER TABLE clientes ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;
ALTER TABLE culturas ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;
ALTER TABLE maquinas ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;
ALTER TABLE manutencao_frota ADD COLUMN IF NOT EXISTS is_deleted int DEFAULT 0;

CREATE TABLE IF NOT EXISTS fornecedores (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    nome text not null,
    contato text,
    telefone text,
    email text,
    observacao text,
    last_updated text not null,
    is_deleted int default 0
);

CREATE TABLE IF NOT EXISTS talhoes (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    nome text not null,
    area_ha numeric,
    cultura_id text,
    status text default 'ATIVO',
    observacao text,
    last_updated text not null,
    is_deleted int default 0
);

CREATE TABLE IF NOT EXISTS equipes (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    nome text not null,
    cargo text not null,
    documento text,
    status text default 'ATIVO',
    last_updated text not null,
    is_deleted int default 0
);

CREATE TABLE IF NOT EXISTS planos_adubacao (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    nome_plano text not null,
    cultura text,
    tipo_aplicacao text,
    area_local text,
    descricao_tecnica text,
    status text default 'PLANEJADO',
    data_criacao text not null,
    data_aplicacao text,
    anexos_uri text,
    last_updated text not null,
    is_deleted int default 0
);

CREATE TABLE IF NOT EXISTS irrigacao (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    talhao_uuid text,
    turno text,
    duracao_min int,
    volumetria_m3 numeric,
    status text default 'CONCLUIDO',
    data text not null,
    observacao text,
    last_updated text not null,
    is_deleted int default 0
);

CREATE TABLE IF NOT EXISTS fertirrigacao (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    talhao_uuid text not null,
    formula text,
    volume_agua_l numeric,
    dosagem_insumo_kg numeric,
    data text not null,
    status text default 'CONCLUIDO',
    observacao text,
    last_updated text not null,
    is_deleted int default 0
);

CREATE TABLE IF NOT EXISTS aplicacoes (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    talhao_uuid text not null,
    produto_nome text not null,
    praga_alvo text,
    dose_ha numeric,
    volume_calda_l numeric,
    data text not null,
    carencia_dias int,
    data_liberacao text,
    last_updated text not null,
    is_deleted int default 0
);

CREATE TABLE IF NOT EXISTS financeiro_transacoes (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    tipo text not null,
    descricao text not null,
    valor numeric not null,
    vencimento text not null,
    data_pagamento text,
    status text default 'PENDENTE',
    categoria text,
    origem_uuid text,
    entidade_nome text,
    last_updated text not null,
    is_deleted int default 0
);

CREATE TABLE IF NOT EXISTS caderno_notas (
    id bigint generated by default as identity primary key,
    uuid uuid unique not null,
    titulo text not null,
    conteudo text,
    data text not null,
    categoria text,
    last_updated text not null,
    is_deleted int default 0
);

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
