name: Fábrica de APK - AgroGB

on:
  push:
    branches:
      - main
      - master
      - v2-release
  workflow_dispatch: # Permite rodar manualmente clicando num botão no GitHub

jobs:
  build:
    name: Gerar APK Android
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Baixando o Código do Repositório
        uses: actions/checkout@v4

      - name: ⚙️ Preparando NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: 🚀 Configurando Expo e EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }} # O token de segurança que fica no GitHub

      - name: 📦 Instalando Dependências do AgroGB
        run: npm ci

      - name: 🏗️ Construindo o APK (Pode levar uns 10 minutos)
        run: eas build --platform android --profile preview --non-interactive

      - name: ✅ Sucesso!
        run: echo "Build finalizada! Você pode baixar o APK direto do site da Expo ou do link que foi gerado acima."
