name: Fábrica de APK - AgroGB

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Permite rodar manualmente clicando num botão no GitHub

jobs:
  build:
    name: Gerar APK Android via Gradle
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./apps/mobile/mobile_app

    steps:
      - name: 📥 Baixando o Código do Repositório
        uses: actions/checkout@v4

      - name: ☕ Configurando Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: ⚙️ Preparando NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./apps/mobile/mobile_app/package-lock.json

      - name: 📦 Instalando Dependências do AgroGB
        run: npm ci

      - name: 🏗️ Construindo o APK Release (Sem Expo EAS)
        working-directory: ./apps/mobile/mobile_app/android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: 📤 Salvando o APK no GitHub (Artefato)
        uses: actions/upload-artifact@v4
        with:
          name: AgroGB-App-Release
          path: ./apps/mobile/mobile_app/android/app/build/outputs/apk/release/app-release.apk
          retention-days: 15
